### ISSUE TITLE
Setting `pkgs` in lib.init has no effect

### ISSUE THREAD

**Issue by MatthewCroughan** [nix-community/dream2nix#95] opened 2022-03-05 06:13 UTC
Setting the `pkgs` argument in `lib.init` does not seem to impact the build.

**Comment by DavHau** [comment] 2022-04-04 13:06
Hey I just tried and `pkgs` worked as expected. If the problems still persists, please add a flake that reproduces the issue. Thanks.

**Comment by DavHau** [comment] 2022-04-24 10:21
Closing due to inability to reproduce the issue

**Closed by DavHau** 2022-04-24 10:21 UTC
