### ISSUE TITLE
exclusion for repos not resolvable on the fly seems to miss something

### ISSUE THREAD

**Issue by happysalada** [nix-community/dream2nix#111] opened 2022-04-06 00:07 UTC
trying to run `nix run .#resolveImpure` inside of nocodb here is the output
```
Run `nix run .#resolveImpure` once to resolve impure projects.
The following projects cannot be resolved on the fly and are therefore excluded:
  nc-lib-gui: packages/nc-lib-gui

Resolving:: Name: nc-lib-gui; Subsystem: nodejs; relPath: packages/nc-lib-gui
```
is it possible that the logic is just inverted ? Instead of not resolving nc-lib-gui it only resolves that one ?

After running that command, you can see that there is only a dream.lock inside that package.

here is the url for the repo if you want to test https://github.com/nocodb/nocodb

**Comment by DavHau** [comment] 2022-04-06 13:57
Oh the warning tells you that you should run `.#resolveImpure` to resolve that project.
Maybe it's confusing, because the moment you execute `.#resolveImpure` that warning is shown one last time. But everything is working as intended. It does resolve exactly that one package which is what it should do.

**Comment by happysalada** [comment] 2022-04-06 20:19
There are 8 packages in that repo, why does it not resolve the other ones ?

**Comment by DavHau** [comment] 2022-04-15 07:37
Because it doesn't need to. The other ones can be translates via a pure translator. This can be done on the fly during each evaluation. Therefore the resolving is not required to achieve reproducibility.
You can still resolve pure projects if you want to to optimize eval performance, by executing `nix run .#{package}.resolve`

**Closed** 2022-04-24 10:46 UTC
